name: TestingRemoteActions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'     
        required: true
     
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: https://github.com/SangarSivasubramaniamTR/Actions/blob/main/.github/actions/remoteaction/action.yaml/setup-tool
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false
        path: ./.github/actions/setup-tool
    - uses: ./.github/actions/setup-tool
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}
