name: TestingRemoteActions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'     
        required: true
    
        
env: 
  TESTING : ${{ secrets.TESTING }}
     
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
        
        
      
      - uses: actions/checkout@v3
      - name: My first step
        uses: ./.github/actions/my-action
        
    
      - uses: actions/checkout@v3
        with:
          repository: SangarSivasubramaniamTR/Actions
          token: ${{ secrets.TTOKEN}}
          persist-credentials: false
          path: ./.github/actions/remoteaction
        
        
      - uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

        
        
    

   
