name: TestingRemoteActions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'     
        required: true
     
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
        
        
      - uses: actions/checkout@v2
        with:
          repository: SangarSivasubramaniamTR/Actions
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/remoteaction
        
        
      - uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

        
        
        
      - uses: actions/checkout@v2

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

      - name: RemoteAction
        uses: ./.github/actions/remoteaction
        with:
          name: ${{ inputs.name }}

   
