name: Powershell on Target Machines

inputs:
  machinename:
    required: true
    description: 'Machine IPs, comma separated values if multiple'
  machineUserName:
    required: true
    description: 'Machine user'
  machinePassword:
    required: true
    description: 'Machine pwd'
  powershellscript:
    required: true
    description: 'Path to the powershell script'
  argument:
    required: false
    description: 'Arguments to be passed to the powershell script'
    
runs:
  using: "composite"
  
  steps:        
     - name: Run powershell on Target Machine       
       shell: pwsh
       run: |
            $password = ConvertTo-SecureString ${{ inputs.machinePassword }} -AsPlainText -Force
            $cred = New-Object System.Management.Automation.PSCredential -ArgumentList "${{ inputs.machineUserName }}", $password
            $command = { powershell -Command "& '${{ inputs.powershellscript }}' ${{ inputs.argument }}" }
            $Servers = ${{ inputs.machinename }}
            foreach ($Server in $Servers)
            {
              Write-Host 'Run powershell on Target Machine:' $Server
              $s = New-PSSession -Computername $Server -credential $cred
              Invoke-Command -Session $s -ScriptBlock $command
              Remove-PSSession -Session $s
            }
