name: Remote Action


    - uses: actions/checkout@v2
      with:
        repository: ./.github/actions/remoteaction/action.yaml/setup-tool
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false
        path: ./.github/actions/setup-tool
    - uses: ./.github/actions/setup-tool
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

inputs:

  name:

    required: true

    description: 'Name to say hello'




runs:

  using: "composite"



  steps:

     - name: Remote Action      

       run: echo "Hello, ${{ inputs.name }}!"
